services:
  dev-env:
    build:
      context: .
      dockerfile: Containerfile
    container_name: venvprimes_dev
    volumes:
      - .:/app:Z
    working_dir: /app
    environment:
      - PIP_BREAK_SYSTEM_PACKAGES=1
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - "8080:8080"
    stdin_open: true # Equivalent to -i
    tty: true        # Equivalent to -t
    command: tail -f /dev/null